{
 "title": "Webserver Access Log Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request duration per resource & vHost (microseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grok_apache2_request_latency_microseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response size per resource & vHost (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "grok_apache2_response_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests/responses per status code & vHost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "grok_apache2_responses_total" }
   ]
  }
 ]
}